version: 2.1
orbs:
  gh: circleci/github-cli@2.0

jobs:
  tf-init:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: terraform init
          command: |
            terraform init -input=false
      - persist_to_workspace:
          root: .
          paths:
            - .

  tf-plan:
    docker:
      - image: hashicorp/terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform plan
          command: |
            terraform plan -out tfapply
            terraform show -no-color tfapply > tfplan-output
      - persist_to_workspace:
          root: .
          paths:
            - .

  tf-apply:
    docker:
      - image: hashicorp/terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  tf-destroy:
    docker:
      - image: hashicorp/terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform plan -destroy -out tfdestroy
            terraform apply -auto-approve tfdestroy

  create-a-pr:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - gh/setup
      - run:
          command: |
            ls -li
            gh pr create --title "make pull request" --body-file tfplan-output
          name: Create Pull Request
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  dev-init-pr:
    jobs:
      - tf-init:
          filters:
            branches:
              only:
                - dev
      - tf-plan:
          requires:
            - tf-init
      - create-a-pr:
          requires:
            - tf-plan

  main-apply:
    jobs:
      - tf-init:
          filters:
            branches:
              only:
                - main
      - tf-destroy:
          requires:
            - tf-init
      - tf-apply:
          requires:
            - tf-destroy

      
